---

- name: Install Prerequisites
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "centos-release-gluster{{ glusterfs_storage_gluster_rel }}"

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - glusterfs-server
    - glusterfs-client
