---

- name: Add PPA for GlusterFS
  apt_repository:
    repo: 'ppa:gluster/glusterfs-{{ glusterfs_storage_ppa_version }}'
    state: present
    update_cache: yes
  register: glusterfs_ppa_added
  when: glusterfs_storage_ppa_use 


- name: Ensure GlusterFS will reinstall if the PPA was just added
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - glusterfs-server
    - glusterfs-client
  when: glusterfs_ppa_added.changed


- name: Ensure GlusterFS is installed
  apt:
    name: "{{ item }}"
    state: installed
    default_release: "{{ glusterfs_storage_gluster_rel }}"
  with_items:
    - glusterfs-server
    - glusterfs-client
